### PR TITLE
Use StringBuilder whenever possible

### PR DESCRIPTION
**Pull request by thc202**
Replace usage of `StringBuffer` with `StringBuilder` where the
synchronisation of the former is not required (and rename the variables
to match the new object).

### CODE REVIEW

**Comment by amesbah** [comment]
Thanks, we applied your changes to be released in 5.0.

**Comment by thc202** [comment]
There are occurrences of `StringBuffer` in [core/src/main/java/com/crawljax/util/XPathHelper.java](https://github.com/crawljax/crawljax/pull/544/files#diff-dd28ec97b9e9a7a32ee7aa7ed9d2838fef7380008bc91979d50f3e4d9727b673) that can be replaced as well.

**Comment by amesbah** [comment]
Thanks, refactored here https://github.com/crawljax/crawljax/blob/frag/core/src/main/java/com/crawljax/util/XPathHelper.java

**Comment by thc202** [comment]
Thank you!

**Pull request closed without merging**
